# version: '1'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/arebelo
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/arebelo
    networks:
      - inception
  # mariadb:
volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      # Whenever a file is changed in the container, the host is also updated
      o: bind
      # Allows to set a local volume
      type: none
      # location of the host to mount
      device: /Users/arebelo/42_inception/srcs/requirements/nginx/arebelo
networks:
  inception:
    driver: bridge