# version: '1'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    networks:
      - inception
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    ports:
      - 9000:9000
    restart: always
    env_file:
      - .env
    networks:
      - inception
  # mariadb:
networks:
  inception:
    driver: bridge