#version: '1'
services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    # image: nginx
    ports:
      - 443:443
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/arebelo
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    # image: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/arebelo
    networks:
      - inception

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
    restart: always
    env_file:
      - .env
    networks:
      - inception
    volumes:
     - mariadb_vol:/var/lib/mysql


volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      # Whenever a file is changed in the container, the host is also updated
      o: bind
      # Allows to set a local volume
      type: none
      # location of the host to mount
      device: /home/ubuntu/42_inception/srcs/requirements/nginx/arebelo
  mariadb_vol:
   driver: local
   driver_opts:
     o: bind
     type: none
     device: /home/ubuntu/42_inception/srcs/requirements/mariadb_vol


networks:
  inception:
    driver: bridge